name: Build for PR

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'data/**/*.json'
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: write # Required to add comments to PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: 🛠️ Build
        run: bun run build
