name: Validate Data Files

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'data/**/*.json'
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: write # Required to add comments to PRs

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Validate JSON files
        run: bun run validate
        
      - name: Run merge test
        run: bun run node scripts/merge.js
        
      # Option 1: Use a dedicated action for PR comments instead
      - name: Add PR comment
        if: github.event_name == 'pull_request' && always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: validation-result
          message: |
            ## Data Validation ${{ job.status == 'success' && '✅' || '❌' }}
            
            ${{ job.status == 'success' && 'All data files are valid!' || 'There are issues with the data files. Please check the action logs for details.' }}